// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: accountmanager/account_manager.proto

package accountmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAccountRequest) Reset() {
	*x = NewAccountRequest{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAccountRequest) ProtoMessage() {}

func (x *NewAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAccountRequest.ProtoReflect.Descriptor instead.
func (*NewAccountRequest) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{0}
}

func (x *NewAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type NewAccountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress   string                 `protobuf:"bytes,1,opt,name=AccountAddress,proto3" json:"AccountAddress,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessToken      string                 `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=RegistrationDate,proto3" json:"RegistrationDate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewAccountResponse) Reset() {
	*x = NewAccountResponse{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAccountResponse) ProtoMessage() {}

func (x *NewAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAccountResponse.ProtoReflect.Descriptor instead.
func (*NewAccountResponse) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{1}
}

func (x *NewAccountResponse) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *NewAccountResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *NewAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *NewAccountResponse) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

type LoginAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountRequest) Reset() {
	*x = LoginAccountRequest{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountRequest) ProtoMessage() {}

func (x *LoginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountRequest.ProtoReflect.Descriptor instead.
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{2}
}

func (x *LoginAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountResponse) Reset() {
	*x = LoginAccountResponse{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountResponse) ProtoMessage() {}

func (x *LoginAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountResponse.ProtoReflect.Descriptor instead.
func (*LoginAccountResponse) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{3}
}

func (x *LoginAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginAccountResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_accountmanager_account_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountmanager_account_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_accountmanager_account_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_accountmanager_account_manager_proto protoreflect.FileDescriptor

const file_accountmanager_account_manager_proto_rawDesc = "" +
	"\n" +
	"$accountmanager/account_manager.proto\x12\x0eaccountmanager\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\x11NewAccountRequest\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"\xca\x01\n" +
	"\x12NewAccountResponse\x12&\n" +
	"\x0eAccountAddress\x18\x01 \x01(\tR\x0eAccountAddress\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12 \n" +
	"\vAccessToken\x18\x03 \x01(\tR\vAccessToken\x12F\n" +
	"\x10RegistrationDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10RegistrationDate\"G\n" +
	"\x13LoginAccountRequest\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\\\n" +
	"\x14LoginAccountResponse\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"F\n" +
	"\x12GetAccountResponse\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"[\n" +
	"\x15ChangePasswordRequest\x12 \n" +
	"\vOldPassword\x18\x01 \x01(\tR\vOldPassword\x12 \n" +
	"\vNewPassword\x18\x02 \x01(\tR\vNewPassword2\xe6\x02\n" +
	"\x0eAccountManager\x12S\n" +
	"\n" +
	"NewAccount\x12!.accountmanager.NewAccountRequest\x1a\".accountmanager.NewAccountResponse\x12Y\n" +
	"\fLoginAccount\x12#.accountmanager.LoginAccountRequest\x1a$.accountmanager.LoginAccountResponse\x12S\n" +
	"\n" +
	"GetAccount\x12!.accountmanager.GetAccountRequest\x1a\".accountmanager.GetAccountResponse\x12O\n" +
	"\x0eChangePassword\x12%.accountmanager.ChangePasswordRequest\x1a\x16.google.protobuf.EmptyB\x14Z\x12pkg/accountmanagerb\x06proto3"

var (
	file_accountmanager_account_manager_proto_rawDescOnce sync.Once
	file_accountmanager_account_manager_proto_rawDescData []byte
)

func file_accountmanager_account_manager_proto_rawDescGZIP() []byte {
	file_accountmanager_account_manager_proto_rawDescOnce.Do(func() {
		file_accountmanager_account_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accountmanager_account_manager_proto_rawDesc), len(file_accountmanager_account_manager_proto_rawDesc)))
	})
	return file_accountmanager_account_manager_proto_rawDescData
}

var file_accountmanager_account_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_accountmanager_account_manager_proto_goTypes = []any{
	(*NewAccountRequest)(nil),     // 0: accountmanager.NewAccountRequest
	(*NewAccountResponse)(nil),    // 1: accountmanager.NewAccountResponse
	(*LoginAccountRequest)(nil),   // 2: accountmanager.LoginAccountRequest
	(*LoginAccountResponse)(nil),  // 3: accountmanager.LoginAccountResponse
	(*GetAccountResponse)(nil),    // 4: accountmanager.GetAccountResponse
	(*GetAccountRequest)(nil),     // 5: accountmanager.GetAccountRequest
	(*ChangePasswordRequest)(nil), // 6: accountmanager.ChangePasswordRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_accountmanager_account_manager_proto_depIdxs = []int32{
	7, // 0: accountmanager.NewAccountResponse.RegistrationDate:type_name -> google.protobuf.Timestamp
	0, // 1: accountmanager.AccountManager.NewAccount:input_type -> accountmanager.NewAccountRequest
	2, // 2: accountmanager.AccountManager.LoginAccount:input_type -> accountmanager.LoginAccountRequest
	5, // 3: accountmanager.AccountManager.GetAccount:input_type -> accountmanager.GetAccountRequest
	6, // 4: accountmanager.AccountManager.ChangePassword:input_type -> accountmanager.ChangePasswordRequest
	1, // 5: accountmanager.AccountManager.NewAccount:output_type -> accountmanager.NewAccountResponse
	3, // 6: accountmanager.AccountManager.LoginAccount:output_type -> accountmanager.LoginAccountResponse
	4, // 7: accountmanager.AccountManager.GetAccount:output_type -> accountmanager.GetAccountResponse
	8, // 8: accountmanager.AccountManager.ChangePassword:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accountmanager_account_manager_proto_init() }
func file_accountmanager_account_manager_proto_init() {
	if File_accountmanager_account_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accountmanager_account_manager_proto_rawDesc), len(file_accountmanager_account_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accountmanager_account_manager_proto_goTypes,
		DependencyIndexes: file_accountmanager_account_manager_proto_depIdxs,
		MessageInfos:      file_accountmanager_account_manager_proto_msgTypes,
	}.Build()
	File_accountmanager_account_manager_proto = out.File
	file_accountmanager_account_manager_proto_goTypes = nil
	file_accountmanager_account_manager_proto_depIdxs = nil
}
